mode: basic
media_root: static
media_url: /static
base_url: /
# If your site is nested inside of a bigger one, you can use media_url and
# base_url to properly generate links on your site. For example, if your URL
# will be some.domain.com/starter/, use:
#   media_url: /starter/media
#   base_url: /starter/
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
 - hyde.ext.plugins.meta.MetaPlugin
 - hyde.ext.plugins.auto_extend.AutoExtendPlugin
 # Plugins needed for the advances section.
 - hyde.ext.plugins.sorter.SorterPlugin
 - hyde.ext.plugins.grouper.GrouperPlugin
 - hyde.ext.plugins.tagger.TaggerPlugin
